### ISSUE TITLE
[Gtk]  NuGet packages

### ISSUE THREAD

**Issue by lytico** [jsuarezruiz/maui-linux#90]
Discussion: Should where be NuGet packages at this early stage of implementation?

**Comment by lytico** [comment]
> @jsuarezruiz wrote: maybe we can start creating some NuGet packages from this point? https://github.com/jsuarezruiz/maui-linux/pull/66#issuecomment-2050172964

> @lytico  wrote: not sure about that, it's really not production ready at all https://github.com/jsuarezruiz/maui-linux/pull/66#issuecomment-2050214832

> @mhrastegari  wrote: Why not a pre-release package? :") https://github.com/jsuarezruiz/maui-linux/pull/66#issuecomment-2050553949

**Comment by mhrastegari** [comment]
Yes! I mean if only BlazorWebView and native navigation works it's totally worth it!

**Comment by kztao** [comment]
i completely agree

**Comment by taha-ghadirian** [comment]
> Yes! I mean if only BlazorWebView and native navigation works it's totally worth it!

That is exactly what we need to kick-start a new MAUI Blazor project on Linux! 
Publishing a pre-release would be greatly appreciated.

**Comment by jsuarezruiz** [comment]
My point of view here would be:
- Create a Nightly feed.
- Add the status to the Wiki and documentation with a link a table with the implementation (every control), etc. and clearly indicate that it is a pre-release. Both in documentation and with versioning.

The reasons would be:
- Allow devs to create apps on Linux. Only with Label, Entry and Button you can create various types of Apps. With Blazor Hybrid open many possibilities. I think that in the current state, although very far from something stable, it can allow the creation of certain types of apps.
- Having devs using it increases the possibilities of increasing the community: having more feedback or who knows, even more devs cooperating with PRs etc.

The disadvantage, it may cause a negative feeling/feedback due to lack of implementations. Could happen, it's a risk, I would say that the solution would be a good Wiki and correctly share the message.

Feedback?

**Comment by ysmoradi** [comment]
@jsuarezruiz Thanks for your efforts

In [bitplatform](https://github.com/bitfoundation/bitplatform#-oss-showcases) we helps developers to write the codes only once and have as much as outputs as possible, and as you can see, the Linux support is missing
![image](https://github.com/jsuarezruiz/maui-linux/assets/5352980/ca8da828-a30d-4802-8e7f-f23544bb7508)

I know there is a fair expectation about quality of a nightly feed provided nupkg

I've the same hope about blazor hybrid and Linux, especially if we become able to test them directly in windows thanks to wslg and Visual Studio.

**Comment by knocte** [comment]
> Feedback?

If by "nightly feed" you mean that each commit to the master branch (or main-linux branch) generates a nuget package that can be consumed by anyone interested, I fully support this idea. We have this approach in FSharpLint: each commit generates a prerelease nuget package. When we feel it is ready for a (non prerelease) nuget package, then we create a git tag and a nuget package with the version of the git tag gets pushed to nuget.org.

Making both nighly feed (prerelease nuget packages) and normal packages live in nuget.org also helps visibility and makes it very easy to consume without the need to subscribe to different nuget sources.

If you want to go ahead with this approach, my team can take care of it (with your guidance) and we will propose a PR.

**Comment by jsuarezruiz** [comment]
> > Feedback?
> 
> If by "nightly feed" you mean that each commit to the master branch (or main-linux branch) generates a nuget package that can be consumed by anyone interested, I fully support this idea. We have this approach in FSharpLint: each commit generates a prerelease nuget package. When we feel it is ready for a (non prerelease) nuget package, then we create a git tag and a nuget package with the version of the git tag gets pushed to nuget.org.
> 
> Making both nighly feed (prerelease nuget packages) and normal packages live in nuget.org also helps visibility and makes it very easy to consume without the need to subscribe to different nuget sources.
> 
> If you want to go ahead with this approach, my team can take care of it (with your guidance) and we will propose a PR.

After reviewing the feedback on this thread, I think we can agree on having a nightly feed to allow easy usage of what's currently available and to help with the visibility of the project. @knocte open an issue, and we'll discuss how to handle it in that thread.

**Comment by mhrastegari** [comment]
Is it possible to debug it directly in Windows with WSLG and Visual Studio?
 
Because .NET MAUI development on Linux with VSCode is not as good as developing on Windows with Visual Studio which has a lot of tools and feature for .NET development! plus VS WSL works like a charm!
 
WSLG:
[Run Linux GUI apps with WSL | Microsoft Learn](https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps)
 
WSL:
[Get started using VS Code with WSL | Microsoft Learn](https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-vscode)
[Debug .NET apps in Linux using WSL - Visual Studio (Windows) | Microsoft Learn](https://learn.microsoft.com/en-us/visualstudio/debugger/debug-dotnet-core-in-wsl-2?view=vs-2022)

**Comment by mhrastegari** [comment]
Hey @jsuarezruiz 
Is it possible to debug it directly in Windows with WSLG and Visual Studio?
 
Because .NET MAUI development on Linux with VSCode is not as good as developing on Windows with Visual Studio which has a lot of tools and feature for .NET development! plus VS WSL works like a charm!
 
WSLG:
[Run Linux GUI apps with WSL | Microsoft Learn](https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps)
 
WSL:
[Get started using VS Code with WSL | Microsoft Learn](https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-vscode)
[Debug .NET apps in Linux using WSL - Visual Studio (Windows) | Microsoft Learn](https://learn.microsoft.com/en-us/visualstudio/debugger/debug-dotnet-core-in-wsl-2?view=vs-2022)
